aboutus/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.decorators.csrf import csrf_exempt
from .views import cariKritik


app_name = 'aboutus'

urlpatterns = [
    path('', views.about, name="about"),
    path('Kritik/', views.addKritik, name="kritik"),
    path('cariKritik/', csrf_exempt(views.cariKritik), name="cariKritik")
]

home/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.create, name='create'),
    path('daftar/', views.daftar, name='create'),
    path('daftar/caricari/', views.searchkasus, name='searchkasus')
]

pac_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('aboutus.urls')),
    path('artikel', include('artikel.urls')),   
    path('hotline/', include('hotline.urls')),
    path('relawan/', include('relawan.urls')),
    path('userlogin/', include('userlogin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userlogin/urls.py
from django.urls import path

from . import views

app_name = 'userlogin'

urlpatterns = [
    path('', views.landing, name="landing"),
    path('signin/', views.signin, name="signin"),
    path('signup/', views.signup, name="signup"),
    path('signout/', views.signout, name="signout")
]

aboutus/models.py
from django.db import models

# Create your models here.
class Kritik(models.Model):
    Username = models.CharField(max_length = 100, default='')
    Date = models.DateField()
    Pesan = models.CharField(max_length = 300, default='')

aboutus/forms.py
from django import forms
from .models import Kritik

class KritikForm(forms.Form):
    Username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Anda',
        'type' : 'text',
        'required' : True,
    }))

    Date = forms.DateField(widget=forms.DateInput(attrs={
        'class' : 'datepicker',
        'type' : 'date',
        'required' : True,
    }))

    Pesan = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Pesan Anda',
        'type' : 'text',
        'required' : True,
    }))

aboutus/views.py
from django.shortcuts import render,redirect
from .models import Kritik
from .forms import KritikForm
from userlogin import views
import json
from django.http import JsonResponse

# Create your views here.
def about(request):
    kritik = Kritik.objects.all()
    form = KritikForm()
    response = {'kritik' : kritik, 'form' : form}
    return render(request, "about.html", response)

def kritik(request):
    return render(request, "kritik_saran.html")

def addKritik(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = KritikForm(request.POST)
            if form.is_valid():
                kritik = Kritik()
                kritik.Username = form.cleaned_data['Username']
                kritik.Date = form.cleaned_data['Date']
                kritik.Pesan = form.cleaned_data['Pesan']
                kritik.save()
            return redirect('aboutus:kritik')
        else:
            kritik = Kritik.objects.all()
            form = KritikForm()
            response = {'kritik' : kritik, 'form' : form}
            return render(request, 'kritik_saran.html', response)

def cariKritik(request):
    if request.method == "POST":
        search = json.loads(request.body).get('searchText')
        kritik1 = Kritik.objects.filter(username__istartswith = search) | Kritik.objects.filter(pesan__istartswith = search)
        hasil = kritik1.values()
        return JsonResponse(list(hasil), safe=False)

aboutus/templates/about.html
<div class="col-md-12">
{% extends 'base.html'%}
{% block title%}
PAC - About Us
{% endblock %}
{% block content %}

{% load static %}
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
<script src="{% static 'about.js' %}"></script>
<style>
    hr { 
        position: relative; 
        top: 20px; 
        border: none; 
        height: 8px; 
        background: chocolate; 
        margin-bottom: 50px; 
        margin-left: 107px;
        margin-right: 107px;
    }
    .responsive {
        width: 300px;
        height: 200px;
    }
    @media (max-width: 767px) {
        .responsive{
            width: 150px;
            height: 100px;
        }
    }
    h1 {
        color: #A82223;
        font-weight: 700;
        font-style: italic;
        font-family: 'Source Sans Pro', sans-serif;
    }
    h2 {
        color: #A82223;
        font-weight: 700;
        font-family: 'Source Sans Pro', sans-serif;
    }
    h6 {
        font-weight: 700;
        font-family: 'Source Sans Pro', sans-serif;
    }
    p {
        font-weight: 400;
        font-family: 'Source Sans Pro', sans-serif;
    }
    .button1 {
        width: 160px;
        height: 50px;
        background: #A82223;
        border-radius: 30px;
        text-align: center;
        color: white;
        font-weight: bold;
    }
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 100%;
        border-radius: 5px;
    }

    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

</style>
<meta charset="UTF-8">
    <div class ="container">
        <img src = "https://wallpapercave.com/wp/wp2553455.jpg"  align="right" alt="Foto Grup" class="responsive"/>
        <h1>ABOUT US</h1>
        <h2>Nama Kelompok</h2>
        <h6>Achmad Fikri Adidharma</h6>
        <h6>Alfred Prasetio</h6>
        <h6>Andhika Rifki Alfariz</h6>
        <h6>Az-zahra Syamsa Rahmita Putri</h6>
        <h6>Maheswara Ananto Argono</h6>
        <div class = "container">
        </div>
    </div>
    <div class="container">
        <h2>About Project</h2>
        <p>Aplikasi yang kami buat ini adalah web yang dapat mencari relawan
            untuk membantu menangani Covid-19 di Indonesia. Web ini juga dapat
            membantu meningkatkan kesadaran diri kita untuk tidak keluar disaat
            pandemi ini agar angka Covid bisa menurun. Web ini juga memberikan
            update data angka pasien Covid di daerah kita yang dapat membantu
            menyadarkan diri kita supaya lebih menjaga diri. Aplikasi ini juga
            memberikan info penting mengenai Satgas Covid supaya kita dapat
            membantu menurunkan angka Covid dan memberikan bantuan jika terdapat
            tersangka positif.</p>
    </div>
    <div class = "container">
        <h2>Goals</h2>
        <p>Tujuan kami membuat aplikasi ini adalah untuk meningkatkan kesadaran penduduk
        Indonesia supaya lebih hati-hati terhadap virus Covid-19.</p>
    </div>
    <hr>
        <div class = "container">
            <input type="text" class="form-control" id="searchIn" placeholder="Search your Keyword">
            <h2>Kritik dan Saran</h2>
            
            <div class="no-result" id="content">
                <p>Hasil Pencarian paling relevan</p>
            </div>
        
            {% for hasil in kritik %}
                <div class="card">
                    Author: {{hasil.Username}}
                    <br>
                    Posted on: {{hasil.Date}}
                    <br>
                    Pesan: {{hasil.Pesan}}
                </div>
                <br>
            {% endfor %}
            <br>
            <div style="text-align: right;">
                {% if user.is_authenticated %}
                <a href="{% url 'aboutus:kritik' %}">
                    <button class="button1" >+ Kritik dan Saran</button>
                </a>
                {% else %}
                <p><a href ="{% url 'userlogin:signin' %}" style="color: blue;">Login</a> terlebih dahulu untuk menambahkan kritik dan saran!</p>
                {% endif %}
            </div>
            <p></p>
        </div>
{% endblock %}
</div>

aboutus/templates/kritik_saran.html
<div class="col-md-12">
{% extends 'base.html'%}
{% block title%}
PAC - Tambah Kritik dan Saran
{% endblock %}
{% block content %}
{% load static %}
<meta charset="UTF-8">
<style>
    .btn{
        display: inline-block;
    }
</style>
    <div class="container">
        <h1>Kritik dan Saran</h1>
        <form action ='' method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn" style="background-color: #A82223; color: white;" value="KIRIM">
        </form>
        <a href="{% url 'aboutus:about' %}">
            <button class="btn btn-icon btn-danger">Batalkan</button>
        </a>
    </div>
</div>
{% endblock %}
 