artikel/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views
from .views import cariArtikel


app_name = 'artikel'


urlpatterns = [
    path('', views.artikel, name='artikel'),
    path('/buatArtikel', views.buatArtikel, name='buatArtikel'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('delete/<str:pk>', views.delete, name='delete'),
    path('delete/komentar/<str:pk>', views.deleteKomentar, name='komentarDelete'),
    path('/cariArtikel', csrf_exempt(views.cariArtikel), name='cariArtikel'),
]

home/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.create, name='create'),
    path('daftar/', views.daftar, name='create'),
    path('daftar/caricari/', views.searchkasus, name='searchkasus')
]

pac_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('aboutus.urls')),
    path('artikel', include('artikel.urls')),   
    path('hotline/', include('hotline.urls')),
    path('relawan/', include('relawan.urls')),
    path('userlogin/', include('userlogin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userlogin/urls.py
from django.urls import path

from . import views

app_name = 'userlogin'

urlpatterns = [
    path('', views.landing, name="landing"),
    path('signin/', views.signin, name="signin"),
    path('signup/', views.signup, name="signup"),
    path('signout/', views.signout, name="signout")
]

artikel/models.py
from django.db import models
# from django.utils timezone
# from datetime import datetime, date

# Create your models here.


class Artikel(models.Model):
    judul = models.CharField(max_length=50)
    penulis = models.CharField(max_length=50)
    gambar = models.ImageField(upload_to = 'images/')
    konten = models.TextField()
    def __str__(self):
        return self.judul

class Komentar(models.Model):
    nama = models.CharField(max_length=50)
    komen = models.TextField()
    artikel = models.ForeignKey(Artikel, on_delete=models.CASCADE)
    def __str__(self):
        return self.komen
    

artikel/forms.py
from django import forms
from .models import Artikel, Komentar

class FormArtikel(forms.ModelForm):
    class Meta:
        model = Artikel
        fields = '__all__'
        widgets = {
            'judul' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Apa judul artikel anda?"
            }),

            'penulis' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Siapa nama anda?"
            }),

            'gambar': forms.FileInput(
                attrs = {
                    'class': 'form-control-file dropzone',
                }),

            'konten' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Silakan tulis konten artikel anda di sini"
            }),
        }

class FormKomentar(forms.ModelForm):
    class Meta:
        model = Komentar
        fields = '__all__' 
        widgets = {
            # 'nama' : forms.TextInput(attrs={
            #     'class': 'form-control',
            #     'placeholder': "Siapa nama anda?"
            # }),

            'komen' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Silakan tulis komentar anda di sini"
            }),
        }

artikel/views.py
from django.shortcuts import render, redirect
from .models import Artikel, Komentar
from .forms import FormArtikel, FormKomentar
from django.contrib import messages
from userlogin import views
import json
from django.http import JsonResponse


# Create your views here.


def artikel(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            formA = FormArtikel(request.POST, request.FILES)
            formB = FormKomentar(request.POST)

            if formA.is_valid():
                formA.save()
                messages.success(request, (f"Artikel {request.POST['judul']} berhasil ditambahkan!"))
                return redirect ('artikel:artikel')
            
            else :
                messages.warning(request, (f"input tidak sesuai!"))
                return redirect('artikel:artikel')
        
        else:
            formA = FormArtikel()
            formB = FormKomentar()
            listArtikel = Artikel.objects.all()
            listKomen = Komentar.objects.all()
            context = {
                'formA' : formA,
                'formB' : formB,
                'listArtikel' : listArtikel,
                'listKomen' : listKomen,
            }
            return render(request, 'artikel/index.html', context)
    
    else:
        listArtikel = Artikel.objects.all()
        listKomen = Komentar.objects.all()
        context = {
            'listArtikel' : listArtikel,
            'listKomen' : listKomen,
        }
        return render(request, 'artikel/index.html', context)



def detail(request, pk):
    artikel = Artikel.objects.get(id=pk)
    listKomen = Komentar.objects.all()

    if request.user.is_authenticated:
        context = {
        'artikel' : artikel,
        'listKomen' : listKomen,
    }

    else : 
        context = {
            'artikel' : artikel,
        }

    if request.method == "POST" :
        formB = FormKomentar(request.POST)

        if formB.is_valid() :
            formB.save()
            messages.success(request, (f"Komentar berhasil ditambahkan!"))
            return redirect('artikel:detail', pk=artikel.pk)
        
        else :
            messages.warning(request, (f"Input tidak sesuai!"))
            return redirect ('artikel:detail', pk=artikel.pk)
    
    else :
        artikel = Artikel.objects.get(id=pk)
        listKomen = Komentar.objects.filter(artikel = artikel)
        formB = FormKomentar(request.POST)
        namaLengkap = request.user.get_username()
        
        context = {
            'artikel' : artikel,
            'formB' : formB,
            'listKomen' : listKomen,
            'namaLengkap' : namaLengkap,
        }
        return render(request, 'artikel/artikel-detail.html', context)


def buatArtikel(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            formA = FormArtikel(request.POST, request.FILES)
            formB = FormKomentar(request.POST)

            if formA.is_valid():
                formA.save()
                messages.success(request, (f"Artikel {request.POST['judul']} berhasil ditambahkan!"))
                return redirect ('artikel:buatArtikel')
            
            else :
                messages.warning(request, (f"input tidak sesuai!"))
                return redirect('artikel:buatArtikel')
        
        else:
            formA = FormArtikel()
            formB = FormKomentar()
            context = {
                'formA' : formA,
                'formB' : formB,
            }
            return render(request, 'artikel/artikel-baru.html', context)


def delete(request, pk):
    artikel = Artikel.objects.get(id=pk)
    artikel.delete()
    # messages.success(request, (f"Artikel {request.GET['artikel']} berhasil dihapus!"))
    messages.success(request, (f"Artikel berhasil dihapus!"))
    return redirect('artikel:artikel')

def deleteKomentar(request,pk):
    komentar = Komentar.objects.get(id=pk)
    Komentar.delete()
    messages.warning(request, (f"{komentar} berhasil dihapus"))
    return redirect('artikel:artikel')


def cariArtikel(request):
    if request.method == 'POST':
        search_str = json.loads(request.body).get('searchText')
        artikels = Artikel.objects.filter(
            judul__istartswith = search_str) | Artikel.objects.filter(
            penulis__istartswith = search_str)

            # judul__istartswith = search_str) | Artikel.objects.filter(
            # penulis__istartswith = search_str) | Artikel.objects.filter(
            # konten__istartswith = search_str)
            
        data = artikels.values()

        # print(data[0].gambar.url)

        return JsonResponse(list(data), safe=False)

artikel/templates/artikel/artikel-baru.html
{% extends 'base.html'%}
{% block title%}
PAC - Artikel
{% endblock %}
{% block content %}
<div class="container py-4">
    <h1 class="display-4 text-center pb-4 border-bottom">Buat Artikel</h1>
    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.judul }}
        </div>
        <div class="col-7 ml-auto">
            {{ formA.penulis }}
        </div>
        {% comment %} <div class="col-7 ml-auto">
            {{ formA.waktu }}
        </div> {% endcomment %}
        {% comment %} <div class="col-7 ml-auto">
            {{ formA.gambar }}
        </div> {% endcomment %}
        <div class="col-7 ml-auto">
            {{ formA.gambar }}
        </div> 
        <div class="col-7 ml-auto">
            {{ formA.konten }}
        </div>

        <button type="submit" class="btn btn-dark col-2 mr-auto">Publis Artikel</button>
    </form>
    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}


    </div>
</div>

{% endblock content %}

artikel/templates/artikel/artikel-detail.html
{% extends 'base.html'%}
{% block title%}
PAC - Artikel
{% endblock %}
{% block content %}

<br>
<h1> {{ artikel.judul }} </h1>
<p>Ditulis oleh : {{ artikel.penulis }} </p>
<img src="{{ artikel.gambar.url }}" width='500px'>
<p> {{ artikel.konten }} </p>

<br>

    {% if user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}
        {% comment %} {{ formB.nama }} {% endcomment %}
        <input name="nama" type="text" value="{{ namaLengkap }}" style="display: none;">
        {{ formB.komen }}
        <input name="artikel" type="text" value="{{ artikel.id }}" style="display: none;">
        <button type="submit" class="btn btn-dark col-6 mt-2">Komentari</button>
        </form>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                  <div class="page-header">
                    <h1> Comments </h1>
                  </div> 
                   <div class="comments-list">
                       {% for komen in listKomen %}
                        {% if komen.artikel.id == artikel.id %} 
                       <div class="media">

                            <div class="media-body">
                                
                              <h4 class="media-heading user_name">{{ namaLengkap }}</h4>
                              {{ komen }}
                              <br>
                            </div>
                        </div>
                        <br>
                         {% endif %}
                             {% endfor %}

                   </div>
                    
                </div>
            </div>
        </div>
    {% else %}
    <p>Ingin berkomentar?? Silakan <a href="{% url 'userlogin:signin' %}" style="color: blue;">sign in</a>!</p>
    {% endif %}


{% comment %} <form method="POST">
    {% csrf_token %}
    {{ formB.nama }}
    {{ formB.komen }}
    <input name="artikel" type="text" value="{{ artikel.id }}" style="display: none;">
    <button type="submit" class="btn btn-dark col-6 mt-2">Komentari</button>
</form> {% endcomment %}



{% comment %} <ul>
    {% for komen in listKomen %}
    {% if komen.artikel.id == artikel.id %}
    <li class="row">
    <h5 class="col-10">{{ komen.nama }}</h5>
        <h5 class="col-10">{{ komen }}</h5>
    </li>
    {% endif %}
    {% endfor %}
</ul> {% endcomment %}

{% comment %} <div class="container">
            <div class="row">
                <div class="col-md-8">
                  <div class="page-header">
                    <h1><small class="pull-right">Comments </h1>
                  </div> 
                   <div class="comments-list">
                       {% for komen in listKomen %}
                        {% if komen.artikel.id == artikel.id %} 
                       <div class="media">
                           <p class="pull-right"><small>5 days ago</small></p>
                            <a class="media-left" href="#"> 
                              <img src="http://lorempixel.com/40/40/people/1/">
                            </a> 
                            <div class="media-body">
                                
                              <h4 class="media-heading user_name">{{ komen.nama }}</h4>
                              {{ komen }}                           
                            </div>
                        {% endif %}
                        {% endfor %}
                        </div>
                   </div>
                </div>
            </div>
        </div> {% endcomment %}


    {% comment %} <div class="container mt-5 mb-5">
    <div class="row height d-flex justify-content-center align-items-center">
        <div class="col-md-7">
            <div class="card">
                <div class="p-3">
                    <h6>Comments</h6>
                </div>
                <div class="mt-3 d-flex flex-row align-items-center p-3 form-color"> <img src="https://i.imgur.com/zQZSWrt.jpg" width="50" class="rounded-circle mr-2"> <input type="text" class="form-control" placeholder="Enter your comment..."> </div>
                <div class="mt-2">   
                        <div class="w-100">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex flex-row align-items-center"> <span class="mr-2">{{ komen.nama }}</span> 
                            </div>
                            <p class="text-justify comment-text mb-0">{{ komen }}</p>
                        </div>
                </div>
            </div>
        </div>
    </div>
    </div> {% endcomment %}

    
    {% comment %} <br>

        <div class="container">
            <div class="row">
                <div class="col-md-8">
                  <div class="page-header">
                    <h1> Comments </h1>
                  </div> 
                   <div class="comments-list">
                       {% for komen in listKomen %}
                        {% if komen.artikel.id == artikel.id %} 
                       <div class="media">

                            <div class="media-body">
                                
                              <h4 class="media-heading user_name">{{ komen.nama }}</h4>
                              {{ komen }}
                              <br>
                            </div>
                        </div>
                        <br>
                         {% endif %}
                             {% endfor %}

                   </div>
                    
                    
                    
                </div>
            </div>
        </div> {% endcomment %}



{% endblock content %}

artikel/templates/artikel/base.html
{% comment %} <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Daftar Kegiatan</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html> {% endcomment %}


<!DOCTYPE html>
<html lang="en">

  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    {% block css %} {% endblock %}

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="#">LOGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">HOME</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">HOTLINE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">VOLUNTEER</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <br>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="row footer-r">
          <div class="col-sm align-self-center">
            <p class="footer-p">Copyright (C) pacil against corona</p>
          </div>
          <div class="col-sm align-self-center">
            <p class="footer-p">email : pac@gmail.com</p>
          </div>
          <div class="col-sm align-self-center">
            <a href="#" class="footer-daftar"><p class="footer-p daftar-p">
              Daftar<br>
              Relawan
            </p></a>
          </div>
        </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

artikel/templates/artikel/index.html
{% extends 'base.html'%}
{% block title%}
PAC - Artikel
{% endblock %}
{% block content %}

{% load static %}
<div class="container py-4">
    <h1 class="display-4 text-center pb-4 border-bottom">Artikel</h1>
    {% comment %} <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="col-7 ml-auto">
            {{ formA.judul }}
        </div>
        <div class="col-7 ml-auto">
            {{ formA.penulis }}
        </div>
        <div class="col-7 ml-auto">
            {{ formA.gambar }}
        </div> 
        <div class="col-7 ml-auto">
            {{ formA.konten }}
        </div>

        <button type="submit" class="btn btn-dark col-2 mr-auto">Publis Artikel</button>
    </form> {% endcomment %}

    <div class="col-4 ">
      <label for="" class="for-search">Cari Artikel Disini</label>
      <input type="text" class="form-control mx-auto" id="searchField" placeholder="Judul/Penulis">
    </div>

    <hr>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}

{% comment %} 
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
            <img class="d-block w-100" src="..." alt="First slide">
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Second slide">
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
{% endcomment %} 

    {% if user.is_authenticated %}
    <a href="{% url 'artikel:buatArtikel' %}" class="btn btn-primary">Buat Artikel</a>
    {% else %}
    <p>Ingin menulis artikel di sini? Silakan <a href="{% url 'userlogin:signin' %}" style="color: blue;">sign in</a>!</p>
    {% endif %}
    
    <div class="fullArtikel">
        <div class="d-flex justify-content-around flex-wrap pb-4">
            {% for artikel in listArtikel %}
            <div class="card" style="width: 18rem;">
                <a href="{% url 'artikel:delete' artikel.id %}" class="col-2">
                    <button type="button" class="close mb-2">&times;</button>
                </a>
                <img src="{{ artikel.gambar.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ artikel.judul }}</h5>
                    <p class="card-text">{{ artikel.konten|slice:":100" }}...</p>
                    <a href="{% url 'artikel:detail' artikel.id %}" class="btn btn-primary">Baca Selengkapnya!</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="no-result">
    <p>No Results Found</p>
  </div>
  <div class="table-output">
    <div class="d-flex flex-wrap justify-content-start" id="content-artikel">
    </div>


    {% comment %} <div class="d-flex justify-content-around flex-wrap pb-4">
        {% for artikel in listArtikel %}
        <div class="card bg-light mt-5" style="width: 18rem;">
            <div class="card-header">
                <div class="row">
                    <h5 class="col-10 mb-2">{{ artikel }}</h5>
                    <a href="{% url 'artikel:detail' artikel.id %}" class="card-link">DETAIL</a>
                    <a href="{% url 'artikel:delete' artikel.id %}" class="col-2">
                        <button type="button" class="close mb-2">&times;</button>
                    </a>
                </div>
                
            </div>
            <div class="card-body">
                <h6 class="card-title">Komentar:</h6>
                <img src="{{ artikel.gambar.url }}">
                <p></p>
                {% comment %} <ul>
                    {% for komen in listKomen %}
                    {% if komen.artikel.id == artikel.id %}
                    <li class="row">
                        <h5 class="col-10">{{ komen }}</h5>
                        <h5 class="col-10">{{ komen.nama }}</h5>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul> 
                <form method="POST">
                    {% csrf_token %}
                    {{ formB.komen }}
                    <input name="artikel" type="text" value="{{ artikel.id }}" style="display: none;">
                    <button type="submit" class="btn btn-dark col-6 mt-2">Komentari</button>
                </form>
            </div>
        </div>
        {% endfor %} {% endcomment %}


    </div>
</div>
 <script src="{% static 'artikel/scripts.js' %}"></script>

{% endblock content %}