home/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.create, name='create'),
    path('daftar/', views.daftar, name='create'),
    path('daftar/caricari/', views.searchkasus, name='searchkasus')
]

pac_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('aboutus.urls')),
    path('artikel', include('artikel.urls')),   
    path('hotline/', include('hotline.urls')),
    path('relawan/', include('relawan.urls')),
    path('userlogin/', include('userlogin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relawan/urls.py
from django.urls import path
from . import views
from .views import DaftarRelawan, ListRelawan, HapusRelawan
from django.views.decorators.csrf import csrf_exempt

app_name = 'relawan'

urlpatterns = [
  path('', ListRelawan.as_view(), name='List-relawan'),
  path('Daftar', DaftarRelawan.as_view(), name='Daftar-relawan'),
  path('Hapus/<int:pk>', HapusRelawan.as_view(), name='Hapus-relawan'),
  path('search_relawan', csrf_exempt(views.search_relawan), name = "search_relawan"),
]

relawan/models.py
from django.db import models
from django.urls import reverse

class Relawan(models.Model):
    nama = models.CharField(max_length=100, default='')
    telp = models.CharField(max_length=20, default='')
    email = models.EmailField(max_length=50, default='')
    swot = models.CharField(max_length=300, default='')
    tertarik = models.CharField(max_length=300, default='')
    alasan = models.CharField(max_length=300, default='')

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        return reverse('relawan:List-relawan')
    
    
    

relawan/forms.py
from django import forms
from .models import Relawan

class RelawanForm(forms.ModelForm):
  class Meta:
    model = Relawan
    fields = [
      'nama',
      'telp',
      'email',
      'swot',
      'tertarik',
      'alasan',
    ]
    labels = {
            'nama': ('Nama Lengkap'),
            'telp': ('Nomor Handphone'),
            'email': ('Email'),
            'swot' : ('SWOT'),
            'tertarik': ('Tertarik'),
            'alasan': ('Alasan menjadi relawan')
        }
    widgets = {
      'nama': forms.TextInput(attrs={
        'placeholder': "Nama Lengkap Anda",
        'class': 'form-control',
        'col':30
        }),
      'telp': forms.TextInput(attrs={
        'placeholder': "Masukkan Nomor handphone Anda",
        'class': 'form-control',
        'col':30
        }),
      'email': forms.TextInput(attrs={
        'placeholder': "Masukkan email Anda",
        'class': 'form-control',
        'col':30
        }),
      'swot': forms.Textarea(attrs={
        'placeholder': "Strength, Weakness, Opportunity, Threat",
        'class': 'form-control'
        }),
      'tertarik' : forms.Textarea(attrs={
        'placeholder': "What are you Interest in",
        'class': 'form-control',
        'col':120
        }),
      'alasan': forms.Textarea(attrs={
        'placeholder': "Mengapa Anda ingin menjadi Relawan",
        'class': 'form-control',
        'col':120
        })
    }

relawan/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .forms import RelawanForm
from .models import Relawan
from django.urls import reverse_lazy
#TK 2
import json
from django.http import JsonResponse

def search_relawan(request):
    if request.method == 'POST':
        search_str = json.loads(request.body).get('searchText')
        relawans = Relawan.objects.filter(
            nama__istartswith = search_str) | Relawan.objects.filter(
            telp__istartswith = search_str) | Relawan.objects.filter(
            email__istartswith = search_str)
            
        data = relawans.values()

        return JsonResponse(list(data), safe=False)

class DaftarRelawan(CreateView):
    model = Relawan
    form_class = RelawanForm
    template_name = 'daftar-relawan.html'

class ListRelawan(ListView):
    model = Relawan
    template_name = 'list-relawan.html'

class HapusRelawan(DeleteView):
    model = Relawan
    template_name = 'hapus-relawan.html'
    success_url = reverse_lazy('relawan:List-relawan')

relawan/templates/daftar-relawan.html
{% extends 'base.html'%}
{% block title%}
PAC - Daftar Relawan
{% endblock %}
{% block content %}
<div class="d-flex flex-column align-items-center">
  <div class="p-3">
    <h1 class="judul-form">
      DAFTAR RELAWAN
    </h1>
  </div>
  <div class="p-1">
    <div class="form-group">
      <form method = "POST">
        <table>
          {% csrf_token %}
          {{ form.as_table}}
        </table>
        <div class="d-flex align-items-center justify-content-center">
          <button type="submit" class="btn btn-danger">Kirim</button>
          <a href="{% url 'relawan:List-relawan' %}">
          <button type="button" class="btn btn-light">Batalkan</button>
          </a>
        </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

relawan/templates/hapus-relawan.html
{% extends 'base.html'%}
{% load static %}
{% block title%}
PAC - Hapus Relawan
{% endblock %}
{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center">
  <div class="p-2">
    <h1 class="judul-form">
      HAPUS RELAWAN!
    </h1>
  </div>
  <form method = "POST" >
    {% csrf_token %}
    <div class="p-2">
      <p>Apakah anda yakin mau menghapus {{relawan.nama}} dari relawan?</p>
      <div class="d-flex align-items-center justify-content-center">
        <button type="submit" class="btn btn-danger" value="Delete" id="dialog" title="Confirmation Required">Hapus</button>
        <a href="{% url 'relawan:List-relawan'%}"><button type="button" class="btn btn-light">Batalkan</button></a>
      </div>
    </div>
  </form>
</div>
<script src="{% static 'js/relawanSearch.js'%}"></script>
{% endblock %}

relawan/templates/list-relawan.html
{% extends 'base.html'%}
{% load static %}
{% block title%}
PAC - Relawan
{% endblock %}
{% block css%}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8">
      <h1 class="title-red">
        RELAWAN
      </h1>
    </div>
    <div class="col-4 ">
      <label for="" class="for-search">Cari Relawan Disini</label>
      <input type="text" class="form-control mx-auto" id="searchField" placeholder="Nama/Telp/Email">
    </div>
  </div>
  <div class="fullRelawan">
    <div class="d-flex flex-wrap justify-content-start">
      {% for relawan in object_list%}
      <div class="p ml-3 mb-3">
        <div class="card" style="width: 22em;">
          <div class="card-body">
            <h5 class="card-title">{{relawan.nama}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{relawan.email}}</h6>
            <p class="card-text">{{relawan.alasan}}</p>
            <a href="#" class="card-link text-primary" data-toggle="modal" data-target="#exampleModal{{ relawan.id }}">Lebih Lanjut</a>
            
              <a href="{% url 'relawan:Hapus-relawan' relawan.pk %}" class="card-link text-danger">[Hapus Relawan]</a>
            
          </div>
        </div>
        <div class=" modal fade" id="exampleModal{{ relawan.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title text-danger" id="exampleModalLabel">{{relawan.nama}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p id="Judul-Modal">SWOT:</p>
                <p class='deskripsi-box' id="Isi-Modal">{{relawan.swot}}</p>
                <p id="Judul-Modal">Minat:</p>
                <p class='deskripsi-box' id="Isi-Modal">{{relawan.tertarik}}</p>
                <p id="Judul-Modal">Alasan ikut Relawan:</p>
                <p class='deskripsi-box' id="Isi-Modal">{{relawan.alasan}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div id="progressbar"></div>
  <div class="no-result">
    <p>No Results Found</p>
  </div>
  <div class="table-output">
    <div class="d-flex flex-wrap justify-content-start" id="content-relawan">
    </div>

  </div>

</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/relawanSearch.js'%}"></script>
{% endblock %}