aboutus/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.decorators.csrf import csrf_exempt
from .views import cariKritik


app_name = 'aboutus'

urlpatterns = [
    path('', views.about, name="about"),
    path('Kritik/', views.addKritik, name="kritik"),
    path('cariKritik/', csrf_exempt(views.cariKritik), name="cariKritik")
]

artikel/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views
from .views import cariArtikel


app_name = 'artikel'


urlpatterns = [
    path('', views.artikel, name='artikel'),
    path('/buatArtikel', views.buatArtikel, name='buatArtikel'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('delete/<str:pk>', views.delete, name='delete'),
    path('delete/komentar/<str:pk>', views.deleteKomentar, name='komentarDelete'),
    path('/cariArtikel', csrf_exempt(views.cariArtikel), name='cariArtikel'),
]

home/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.create, name='create'),
    path('daftar/', views.daftar, name='create'),
    path('daftar/caricari/', views.searchkasus, name='searchkasus')
]

hotline/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'hotline'

urlpatterns = [
    path('', views.html_home_hotline, name='html_home_hotline'),
    path('addhotline', views.html_add_hotline, name='html_add_hotline'),
    path('getData/', views.get_list_RS, name='data'),
]

pac_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('aboutus.urls')),
    path('artikel', include('artikel.urls')),   
    path('hotline/', include('hotline.urls')),
    path('relawan/', include('relawan.urls')),
    path('userlogin/', include('userlogin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relawan/urls.py
from django.urls import path
from . import views
from .views import DaftarRelawan, ListRelawan, HapusRelawan
from django.views.decorators.csrf import csrf_exempt

app_name = 'relawan'

urlpatterns = [
  path('', ListRelawan.as_view(), name='List-relawan'),
  path('Daftar', DaftarRelawan.as_view(), name='Daftar-relawan'),
  path('Hapus/<int:pk>', HapusRelawan.as_view(), name='Hapus-relawan'),
  path('search_relawan', csrf_exempt(views.search_relawan), name = "search_relawan"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href= "{% static 'style.css' %}" type="text/css">
    {% block css%} {% endblock %}

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="#">
            <img src="{% static 'pacman.png' %}" alt="" id="foto-kecil" style="width: 3vw; height: 3vw;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:index' %}">HOME</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'artikel:artikel' %}">ARTIKEL</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'aboutus:about' %}">ABOUT</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{% url 'hotline:html_home_hotline' %}">HOTLINE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'relawan:List-relawan' %}">VOLUNTEER</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <br>
    {% block content %}
    {% endblock %}
    <footer>
      <div class="container-fluid footer-container">
        <div class="row footer-r">
          <div class="col-sm align-self-center">
            <p class="footer-p">Copyright (C) pacil against corona</p>
          </div>
          <div class="col-sm align-self-center">
            <p class="footer-p">email : pac@gmail.com</p>
          </div>
          <div class="col-sm align-self-center">
            <a href="{% url 'relawan:Daftar-relawan' %}" class="footer-daftar"><p class="footer-p daftar-p">
              Daftar<br>
              Relawan
            </p></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>